import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/alumnidirectory">AlumniDirectory</Link>
        </li>
        <li>
          <Link to="/jobportal">JobPortal</Link>
        </li>
        <li>
          <Link to="/homepage">Homepage</Link>
        </li>
        <li>
          <Link to="/events">Events</Link>
        </li>
        <li>
          <Link to="/alumnifeed">AlumniFeed</Link>
        </li>
        <li>
          <Link to="/donations">Donations</Link>
        </li>
        <li>
          <Link to="/photogallery">PhotoGallery</Link>
        </li>
        <li>
          <Link to="/membership">Membership</Link>
        </li>
        <li>
          <Link to="/scholarship">Scholarship</Link>
        </li>
        <li>
          <Link to="/admindashboard">AdminDashboard</Link>
        </li>
        <li>
          <Link to="/profile">Profile</Link>
        </li>
        <li>
          <Link to="/createpost">CreatePost</Link>
        </li>
        <li>
          <Link to="/groups">Groups</Link>
        </li>
        <li>
          <Link to="/photogallerysub">PhotoGallerySub</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
